name: Build Sphinx Docs

on:
  push:
    branches: [ main ] # 当 main 分支有更新时触发
  pull_request:
    branches: [ main ] # 当有 PR 指向 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用 3.x 版本的 Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # 假设您已经创建了 requirements.txt

    - name: Build HTML
      run: |
        make html # 或者使用 sphinx-build source build/html